// <auto-generated />
namespace Hdy.Media.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _23423423 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_23423423));
        
        string IMigrationMetadata.Id
        {
            get { return "201612281138215_23423423"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
