// <auto-generated />
namespace Hdy.Media.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _234235656 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_234235656));
        
        string IMigrationMetadata.Id
        {
            get { return "201612200726263_234235656"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
