// <auto-generated />
namespace Hdy.Media.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _432423456666 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_432423456666));
        
        string IMigrationMetadata.Id
        {
            get { return "201701151238459_432423456666"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
